### ISSUE TITLE
error installing in v16

### ISSUE THREAD

**Issue by ygol** [camptocamp/odoo-repository#5]
Hello,
getting the following error trying to install in a clean DB
```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1589, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1616, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1820, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 466, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 468, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_module.py", line 592, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-16>", line 2, in new
  File "/opt/odoo/custom/src/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 488, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 188, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/odoo/custom/src/odoo/odoo/modules/module.py", line 468, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/opt/odoo/auto/addons/odoo_repository/__init__.py", line 1, in <module>
    from . import models
  File "/opt/odoo/auto/addons/odoo_repository/models/__init__.py", line 12, in <module>
    from . import odoo_repository
  File "/opt/odoo/auto/addons/odoo_repository/models/odoo_repository.py", line 13, in <module>
    from ..utils.scanner import RepositoryScannerOdooEnv
  File "/opt/odoo/auto/addons/odoo_repository/utils/scanner.py", line 4, in <module>
    from ..lib.scanner import RepositoryScanner
  File "/opt/odoo/auto/addons/odoo_repository/lib/scanner.py", line 260, in <module>
    class MigrationScanner(BaseScanner):
  File "/opt/odoo/auto/addons/odoo_repository/lib/scanner.py", line 267, in MigrationScanner
    migration_paths: list[tuple[str]],
TypeError: 'type' object is not subscriptable

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://127.0.0.1:16069/web/assets/196-dba12f2/web.assets_backend.min.js:987:163)
    at XMLHttpRequest.<anonymous> (http://127.0.0.1:16069/web/assets/196-dba12f2/web.assets_backend.min.js:995:13)
```

**Comment by ygol** [comment]
The error seems to be caused when using a python version below 3.9
I manage to have the app installed after
adding:
`from typing import List, Tuple`

and replace *list* and *tuple* with `List` and `Tuple` in  /lib/scanner.py
